### ISSUE TITLE
Can your provide some example?

### ISSUE THREAD

**Issue by 0xairdropfarmer** [datalogix/tall-kit#18]
I didn't know how to use this. can your give some example?

**Comment by ricardogobbosouza** [comment]
Hi @krissnawat 

## Installation

```bash
composer require datalogix/tall-kit
```

Remember to install tailwind:
https://tailwindcss.com/docs/guides/laravel

## Components

List of all components:
https://github.com/datalogix/tall-kit/blob/main/config/tall-kit.php#L8

At the moment we have several components, here is an example of using some:

### Alerts
```blade
<x-alert title = "Warning" type = "warning">
   Custom message
</x-alert>
```

### Forms
```blade
<x-form>
   <x-input name = "Name" />
   <x-select name = "Options": options = "[]" />
   <x-trix name = "editor" />
   <x-submit />
</x-form>
```

### Tables
```blade
<x-table>
   <x-slot name = "head">
     <x-heading: sortable = "false"> Name </x-heading>
     <x-heading: sortable = "false"> Email </x-heading>
   </x-slot>
   <x-row>
     <x-cell> Name </x-cell>
     <x-cell> email@email.com </x-cell>
   </x-row>
</x-table>
```

## Themes
You can customize as needed:
https://github.com/datalogix/tall-kit/blob/main/config/tall-kit.php#L116

If you want to change the input style:
https://github.com/datalogix/tall-kit/blob/main/config/tall-kit.php#L569


## Roadmap v1
I'm working to try to launch at the beginning of the year

- Documentation
- Website with examples
- Increase coverage
- More components

**Comment by 0xairdropfarmer** [comment]
@ricardogobbosouza thank your

**Comment by 0xairdropfarmer** [comment]
@ricardogobbosouza  can your give an example for the all editor. I have tried to use quill editor but didn't work

**Comment by ricardogobbosouza** [comment]
Sure, you need to inject `@tallkitStyles` and `@tallkitScripts`.

eg:
```blade
<x-html>
  <x-quill name="editor1" /> // https://quilljs.com/
  <x-easymde name="editor2" /> // https://easy-markdown-editor.tk/
  <x-trix name="editor3" /> // https://trix-editor.org/

  @tallkitStyles ---> inject styles
  @tallkitScripts ---> inject scripts
</x-html>
```

**Comment by ricardogobbosouza** [comment]
@krissnawat it works?

**Comment by 0xairdropfarmer** [comment]
@ricardogobbosouza thank it's work

**Comment by ricardogobbosouza** [comment]
Hi @krissnawat 
Coming soon https://tall-kit.netlify.app/
